### ISSUE TITLE
Can't call jsonify as described

### ISSUE THREAD

**Issue by mosesontheweb** [corydolphin/flask-jsonpify#15]
Hi there,

I just went through a tutorial which was mentioning flask-jsonpify to be included. Therefore I installed it using pip and added the line as described in your manual. Actually it does not work. Callback is:

```
Traceback (most recent call last):
  File "chinook_api.py", line 5, in <module>
    from flask.ext.jsonpify import jsonify
ModuleNotFoundError: No module named 'flask.ext'
```

There's no flask/ext/ directory, flask_jsonpify is directly installed under site-packges. Any hints to this?

Many thanks in advance!

Regards, Thomas

**Comment by corydolphin** [comment]
Hey there!

That was previously an alias Flask helped to facilitate. import from “flask_jsonpify”

**Comment by Akonibrahim** [comment]
@corydolphin Hi cory Thanks
from flask_jsonpify import jsonify
That's worked

**Comment by VitaliLupusor** [comment]
Nowadays you can import jasonify directly from flask.

The code should look like:
`from flask import jsonify`

**Comment by daghan** [comment]
@Vitali-Lupusor, flask_jsonpify is different than core flask.jsonify
