### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by mattflaschen** [corydolphin/flask-jsonpify#7]
There are some [useful changes](https://github.com/CoryDolphin/flask-jsonpify/compare/v1.3...master) since the latest release [on PyPI](https://pypi.python.org/pypi/Flask-Jsonpify) (1.3).

These include the application/javascript fix (#3).

**Comment by CoryDolphin** [comment]
Hey @mattflaschen you are totally right. I tried to push a release out tonight, but having some travis issues. I will do this tomorrow ASAP.

Thanks for the nudge and sorry for the delay

**Comment by corydolphin** [comment]
Sorry for the delay! It is now live!

https://pypi.python.org/pypi?name=Flask-Jsonpify&version=1.5.0&:action=display
